
E:\E-MAIL SOFTWARE V1.1.5\zelcore>python zel_gemeni_1.py
--- ПОИСК ИСТОЧНИКА ПРИВАТНОГО КЛЮЧА ---

[!] Найдено 'privKeyWIF' в файле: Account-BsIPcGz7.js
--------------------------------------------------
tore.dispatch("obtainMarkets"),this.$store.commit("updateOverviewStyle","b"),this.$store.dispatch("saveAccount")},changeTxsNotifications(){this.txsNotifications=!this.txsNotifications;const e=this.txsNotifications;this.$store.commit("changeTransactionsNotifications",e),this.$store.dispatch("saveAccount"),console.log("change Transactions Notifications")},choosepk(e){console.log(e),this.selectedpkpath=this.coins[e].name,this.selectedcoin=e,this.selectedpk=this.coins[e].addresses[this.walletValue].privKeyWIF||this.coins.ethereum.addresses[this.walletValue].privKeyWIF},chooseAvatar(){const e=this,{files:t}=this.$refs.image,l=t[0].path.replace(/\\/g,"/").replace(/ /g,"%20");this.$store.commit("selectAvatar",l),this.$store.dispatch("saveAccount"),this.$store.commit("togglePanelVisible",!1),setTimeout(()=>{e.$store.commit("togglePanelVisible",!0)})},chooseBG(){this.$store.commit("changeZelCoreClassic",!0),this.$store.commit("updateClassicZelCore",!0),this.$localstore.set("zelcoreClassic",!0);const{files:e}=this.$refs.imagebg,h=e[0].path.replace(/\\/g,"/").replace(/ /g,"%20");this.$store.commit("selectBG",h),this.$store.dispatch("saveAccount")},resetBG(){this.$store.commit("resetBG"),this.$store.dispatch("saveAccount"),this.resetBackgroundDialogVisible=!1},resetAvatar(){this.$store.commit("resetAvatar"),this.$store.dispatch("saveAccount"),this.resetBackgroundDialogVisible=!1},copyToClipboard(e){e&&this.$store.dispatch("copyToClipboard",e)},autologoutfn(){const e=document.getElementBy
--------------------------------------------------

[!] Найдено 'privKeyWIF' в файле: AlgoTokenDialog-DSm38TZS.js
--------------------------------------------------
=this.importToken,{decimals:s}=this.importToken;if(!o||!m||!l||!s){this.$message.error(this.$t("message.missing_token_specs"));return}if(Object.keys(this.coins).find(t=>this.coins[t].assetId?+this.coins[t].assetId==+o:+this.coins[t].assetId==+o)){this.$message.error(this.$t("message.specs_exists"));return}const f={coin:`algo${o}`,name:`${m} ALGO`,uri:[m.split(" ").join("").toLowerCase(),l.toLowerCase()],addresses:new Array(12).fill().map((t,k)=>({address:this.coins.algorand.addresses[k].address,privKeyWIF:this.coins.algorand.addresses[k].privKeyWIF,confirmed:0,unconfirmed:0,minBalance:0,spendable:!1,transactions:[]})),unit:l,type:"algorand",coinType:"token",logolink:"@/assets/logos/NoImage.svg",fee:.001,feepolicy:{economy:1,normal:1,fast:2},assetId:Number(o),color:"#ffffff",decimals:Number(s),explorer:g.algorand.explorer,node:g.algorand.node,api:g.algorand.api};this.$store.commit("importALGOTokens",[f]),this.$store.commit("saveALGOTokensToAccount",JSON.parse(JSON.stringify(this.importToken))),this.showPopupDialog=!1,setTimeout(()=>{e.importToken.contract="",e.importToken.name="",e.importToken.decimals=18,e.importToken.unit=""}),this.$store.commit("addCoin",{coin:`algo${o}`}),this.$store.dispatch("saveAccount")}}},y=["placeholder"],A=["placeholder"],D=["placeholder"],I=["placeholder"];function P(e,o,m,l,s,p){const c=T("ZelButton"),f=T("ElDialog");return b(),v(f,{"model-value":s.showPopupDialog,title:e.$t("message.import_algo_token"),width:"80%","append-to-body":"",onClose:o[5]
--------------------------------------------------

[!] Найдено 'zelid' в файле: AppSelector-CHQnjy6C.js
--------------------------------------------------
input__controls"},jS={class:"control-group"},eb={class:"control-group__label"},tb={class:"slider-container"},nb={class:"slider-value"},rb={class:"value-number"},ab={class:"value-unit"},ib={class:"loginless-input__actions"},ob={class:"loginless-input__footer"},sb={class:"footer__text"},cb={__name:"LoginLessInput",emits:["closeDialog"],setup(t,{emit:e}){const n=e,r=()=>{n("closeDialog")},{runOnFluxConnect:a}=I_(),i=Rn("syncGlobalState"),s=Rn("loadGlobalState"),o=Rn("TAGS"),c=b_(),l=ot(()=>c.state.zelid.bitcoin),u=ot(()=>c.state.loggedaccount[0].username),_=ot(()=>c.state.fluxAI[o.FLUXLOGINLESS]),m=ot(()=>_.value?_.value.fluxId!==l.value:!1),p=Uu(30),d=async()=>{await c.dispatch("loadFluxAILoginLess",{tag:o.FLUXLOGINLESS});const g=await a(p.value);if(g){const f=await c.dispatch("getFluxAIkey"),b={fluxId:l.value,username:u.value,token:g,derivedKeyAndSalt:f};i(o.FLUXLOGINLESS,b),await c.dispatch("saveFluxAILoginLess",{tag:o.FLUXLOGINLESS}),Ie.$message.success(Ie.$t("message.ai_grant_success"))}else Ie.$message.error(Ie.$t("message.ai_auth_failed"));r()},S=async()=>{await c.dispatch("loadFluxAILoginLess",{tag:o.FLUXLOGINLESS}),s(o.FLUXLOGINLESS)?(await c.dispatch("deleteFluxAILoginLess",{tag:o.FLUXLOGINLESS}),i(o.FLUXLOGINLESS,null,!1),Ie.$message.success(Ie.$t("message.ai_auth_rev_success"))):Ie.$message.error(Ie.$t("message.ai_auth_grant_not_exist")),r()};return Bu(async()=>{await c.dispatch("loadFluxAILoginLess",{tag:o.FLUXLOGINLESS})}),(g,f)=>{const b=ke("Icon"),T=ke("ElSlider"
--------------------------------------------------

[!] Найдено 'privKeyWIF' в файле: b-coins-7QuJVfZY.js
--------------------------------------------------
const e={coin:"zelcash",name:"Flux",uri:["flux","zelcash","zel"],pubKeyHash:"1cb8",scriptHash:"1cbd",messagePrefix:`Zelcash Signed Message:
`,wif:"80",normalAddress:"t1",normalAddressB:"t1",scriptAddress:"t3",scriptAddressB:"t3",slip:19167,addresses:[{address:"",privKeyWIF:"",confirmed:0,unconfirmed:0,transactions:[]},{address:"",privKeyWIF:"",confirmed:0,unconfirmed:0,transactions:[]},{address:"",privKeyWIF:"",confirmed:0,unconfirmed:0,transactions:[]},{address:"",privKeyWIF:"",confirmed:0,unconfirmed:0,transactions:[]},{address:"",privKeyWIF:"",confirmed:0,unconfirmed:0,transactions:[]},{address:"",privKeyWIF:"",confirmed:0,unconfirmed:0,transactions:[]},{address:"",privKeyWIF:"",confirmed:0,unconfirmed:0,transactions:[]},{address:"",privKeyWIF:"",confirmed:0,unconfirmed:0,transactions:[]},{address:"",privKeyWIF:"",confirmed:0,unconfirmed:0,transactions:[]},{address:"",privKeyWIF:"",confirmed:0,unconfirmed:0,transactions:[]},{address:"",privKeyWIF:"",confirmed:0,unconfirmed:0,transactions:[]},{address:"",privKeyWIF:"",confirmed:0,unconfirmed:0,transactions:[]}],pathlinux:"zelcash",pathmac:"Zelcash",path:"Zelcash",config:"zelcash",newconfig:"flux",newpathlinux:"flux",newpathmac:"Flux",newpath:"Flux",unit:"FLUX",rpcport:16124,testnetrpcport:26
--------------------------------------------------

[!] Найдено 'privKeyWIF' в файле: Bep2TokenDialog-DYEsg0Ud.js
--------------------------------------------------
als:i}=this.importToken;if(!o||!m||!p||!i){e.$message.error(e.$t("message.missing_token_specs"));return}if(Object.keys(this.coins).find(t=>this.coins[t].identifier?this.coins[t].identifier.toLowerCase()===o.toLowerCase():this.coins[t].identifier===o)){e.$message.error(e.$t("message.specs_exists"));return}const f={coin:`bnb${o}`,name:`${m} BEP2`,uri:[m.split(" ").join("").toLowerCase(),p.toLowerCase()],addresses:new Array(12).fill().map((t,T)=>({address:this.coins.bnbbinance.addresses[T].address,privKeyWIF:this.coins.bnbbinance.addresses[T].privKeyWIF,confirmed:0,unconfirmed:0,transactions:[]})),unit:p,type:"bnb",coinType:"token",logolink:"@/assets/logos/NoImage.svg",fee:375e-6,feepolicy:{economy:.5,normal:1,fast:2},color:"#ffffff",decimals:Number(i),identifier:o,explorer:k.bnb.explorer,node:k.bnb.node,api:k.bnb.api};this.$store.commit("importBEP2Tokens",[f]),this.$store.commit("saveBEP2TokensToAccount",JSON.parse(JSON.stringify(this.importToken))),this.showPopupDialog=!1,setTimeout(()=>{e.importToken.contract="",e.importToken.name="",e.importToken.decimals=8,e.importToken.unit=""}),this.$store.commit("addCoin",{coin:`bnb${o}`}),this.$store.dispatch("saveAccount")}}},v=["placeholder"],y=["placeholder"],B=["placeholder"],D=["placeholder"];function E(e,o,m,p,i,l){const c=g("ZelButton"),f=g("ElDialog");return $(),w(f,{"model-value":i.showPopupDialog,title:e.$t("message.import_bnb_token"),width:"80%","append-to-body":"",onClose:o[5]||(o[5]=t=>l.closePopup())},{footer:a(()=>[b(c,{r
--------------------------------------------------

[!] Найдено 'privKeyWIF' в файле: CoinOverview-CTezK7YW.js
--------------------------------------------------
Je.PublicKey(this.coins.solana.addresses[this.activeWallet].address),r=Ss(d,n,i,a);console.log(r);const l=new Je.PublicKey(this.coins.solana.addresses[this.activeWallet].address),c=await s.getLatestBlockhash("finalized"),f=new Je.Transaction({blockhash:c.blockhash,feePayer:l,lastValidBlockHeight:c.lastValidBlockHeight});f.add(r);const T=Je.ComputeBudgetProgram.setComputeUnitPrice({microLamports:6e4});f.add(T);const F=Je.Keypair.fromSecretKey(G.from(this.coins.solana.addresses[this.activeWallet].privKeyWIF,"hex"));f.sign(F);const A=f.serialize(),O=await s.sendRawTransaction(A,{preflightCommitment:"confirmed"});console.log(O);const k=this;setTimeout(()=>{k.solanaAccountInfo()},5e3),setTimeout(()=>{k.$message.success(k.$t("message.spl_creation_success"))},8e3),setTimeout(()=>{k.solanaAccountInfo()},1e4),setTimeout(()=>{k.$store.commit("hardWorking",!1),k.solanaAccountInfo()},15e3)}catch(e){this.$store.commit("hardWorking",!1),this.$log.error(e),this.$message.error(e.message||e)}},async paste(e){},async solanaAccountInfo(){try{const e=this;this.activeCoin==="solana"&&(this.solanaSPLaddressExists=!0);const t=this.loggedaccount[0].apiService.solana||this.coins.solana.api[0],s=e.$localstore.get("proxyServer")+t,a=this.coinData.addresses[this.activeWallet].address,n={jsonrpc:"2.0",id:Math.random().toString(36).slice(2)+Math.random().toString(36).slice(2),method:"getAccountInfo",params:[a,{encoding:"jsonParsed",commitment:"processed"}]};e.$http.post(s,n).then(i=>{i.data.result&&i.data
--------------------------------------------------

[!] Найдено 'privKeyWIF' в файле: ErgoTokenDialog-DRWmsSRL.js
--------------------------------------------------
en;if(!o||!m||!p||!s){this.$message.error(this.$t("message.missing_token_specs"));return}if(Object.keys(this.coins).find(t=>this.coins[t].contractAddress?this.coins[t].contractAddress.toLowerCase()===o.toLowerCase():this.coins[t].contractAddress===o)){this.$message.error(this.$t("message.specs_exists"));return}const f={coin:`ergo${o}`,name:`${m} ERG`,uri:[m.split(" ").join("").toLowerCase(),p.toLowerCase()],addresses:new Array(12).fill().map((t,g)=>({address:this.coins.ergo.addresses[g].address,privKeyWIF:this.coins.ergo.addresses[g].privKeyWIF,confirmed:0,unconfirmed:0,transactions:[]})),unit:p,type:"ergo",coinType:"token",logolink:"@/assets/logos/NoImage.svg",fee:.001,feepolicy:{economy:1,normal:1.1,fast:2},contractAddress:o,color:"#ffffff",decimals:Number(s),explorer:k.ergo.explorer,node:k.ergo.node,api:k.ergo.api};this.$store.commit("importERGOTokens",[f]),this.$store.commit("saveERGOTokensToAccount",JSON.parse(JSON.stringify(this.importToken))),this.showPopupDialog=!1,setTimeout(()=>{e.importToken.contract="",e.importToken.name="",e.importToken.decimals=18,e.importToken.unit=""}),this.$store.commit("addCoin",{coin:`ergo${o}`}),this.$store.dispatch("saveAccount")}}},b=["placeholder"],D=["placeholder"],E=["placeholder"],P=["placeholder"];function A(e,o,m,p,s,l){const c=T("ZelButton"),f=T("ElDialog");return w(),v(f,{"model-value":s.showPopupDialog,title:e.$t("message.import_ergo_token"),width:"80%","append-to-body":"",onClose:o[5]||(o[5]=t=>l.closePopup())},{footer:a(()=>[h
--------------------------------------------------

[!] Найдено 'privKeyWIF' в файле: FioCryptoHandle-WFNFZHDL.js
--------------------------------------------------
.$localstore.get("proxyServer")+l}/v1/chain/avail_check`,t={fio_name:s+e.fiodomain},n=(await e.$http.post(i,t)).data.is_registered;e.fioCryptoHandleCheckAvailability=n!==1}catch(l){e.fioCryptoHandleCheckAvailability=!1,this.$log.error(l)}},800)},async registerFioCryptoHandle(){try{this.$store.commit("hardWorking",!0);const s=this,e="fio",l=s.loggedaccount[0].nodeService[e]||s.coins[e].node[0],c=`${s.$localstore.get("proxyServer")+l}/v1/`,i=async(A,v={})=>fetch(A,v),t=this.coins.fio.addresses[0].privKeyWIF,o=this.coins.fio.addresses[0].address,n=10**s.coins.fio.decimals,p=100,m=new F(n.toString()),_=new F(p).multipliedBy(m).toFixed();if(this.coins.fio.addresses[0].confirmed<p){this.$store.commit("hardWorking",!1),s.$message.error(s.$t("message.fio_balance_error"));return}const C=new T(t,o,c,i),a=this.fioCryptoHandlecheckAvailableInput+this.fiodomain,r=await C.genericAction("pushTransaction",{action:"regaddress",account:"fio.address",data:{fio_address:a,owner_fio_public_key:o,max_fee:Number(_),tpid:"foundation@zelcore"}});console.log(r),s.fioCryptoHandlecheckAvailableInput="",s.fioSetupDialogVisible=!1,s.fioCryptoHandleCheckAvailability=!1,this.fioCryptoHandle=a,this.fioCryptoHandles.push(a),s.$message.success(s.$t("message.fio_registered")),s.currenciesMapping.length>0?(setTimeout(async()=>{s.$message.info(s.$t("message.fio_mapping"))},5e3),setTimeout(async()=>{s.$store.commit("hardWorking",!1),s.mapFioCryptoHandleAddresses()},8e3)):s.$store.commit("hardWorking",!1)}catch(s){t
--------------------------------------------------

[!] Найдено 'zelid' в файле: FluxDrive-BocJp1TT.js
--------------------------------------------------
&(t.subscriptionError.value=!0),t.isPremiumUser&&(t.isPremiumUser.value=!1)),t.storage&&(t.storage.value=r.storage),r}class Wt{constructor(){this.authCache={loginPhrase:null,signature:null,lastRefresh:null}}createAxiosInstance(){const t=Gr.create({baseURL:Jr.BASE_URL,timeout:en.DEFAULT_REQUEST,headers:{"Content-Type":"application/json"}});return t.interceptors.request.use(async r=>{if(r.method==="post"&&!(r.data instanceof FormData)){const n=await this.getAuthHeaders();n&&(r.data={...r.data||{},zelid:n.zelid,loginPhrase:n.loginphrase,signature:n.signature})}return r},r=>Promise.reject(r)),t.interceptors.response.use(r=>{if(r.data?.error){if(r.data.error.includes("subscription")){const s=new hr(r.data.error);return s.response=r,Promise.reject(s)}if(r.data.error.includes("Storage space exceeded")){const s=new yn(r.data.error);return s.response=r,Promise.reject(s)}if(r.data.error.includes("Error getting subscription")||r.data.error.includes("Error obtaining subscription")){const s=new In(r.data.error);return s.response=r,Promise.reject(s)}if(r.data.error.includes("File size exceeds")){const s=new wn(r.data.error,"TOO_LARGE");return s.response=r,Promise.reject(s)}if(r.data.error.includes("Invalid folder name")||r.data.error.includes("Invalid parent folder")){const s=new rt(r.data.error);return s.response=r,Promise.reject(s)}const n=new Error(r.data.error);return n.response=r,Promise.reject(n)}if(r.data?.warning&&typeof r.data.warning=="string"&&(r.data.warning.includes("login")||
--------------------------------------------------

[!] Найдено 'privKeyWIF' в файле: FluxNodesApp-CYp0vZaU.js
--------------------------------------------------
g",props:De(["visible","selectedFluxNodeForEdit"],{modelValue:{},modelModifiers:{}}),emits:De(["dialogVisibillity"],["update:modelValue"]),setup(A,{emit:g}){const i=ze||Le,m=A,r=g,o=Ke(A,"modelValue"),{copyToClipboard:p}=Pe(),d=ye(),{coins:D}=Ce(),z=Se(),{myFluxNodes:P}=Oe("myFluxNodes"),U=j(""),L=Q(()=>U.value!==o.value.fluxNodeIP),w=Q(()=>{if(!o.value?.fluxNode?.fluxnodepk||!o.value?.fluxNodeAddr)return null;const h=D.value.zelcash.addresses.find(c=>c.address===o.value.fluxNodeAddr);if(!h||!h.privKeyWIF||typeof h.privKeyWIF!="string")return null;try{let c=h.privKeyWIF;return c.length!==64&&(c=i.address.WIFToPrivKey(c)),i.address.privKeyToPubKey(c,!0)}catch{return null}}),y=()=>{r("dialogVisibillity",{dialog:"editFluxnodeDialogVisible",value:!1})},v=async h=>{const c="zelcash",k=z.value.apiService[c]||D.value[c].api[0],B=`${t.$localstore.get("proxyServer")}${k}fluxnode/listfluxnodes/${h}`;let re=[];const te=await t.axios.get(B,{timeout:1e4}).catch(oe=>{t.$log.error(oe),t.$message.error(t.$t("message.error_getting_zelnodes"))});return te&&(re=te.data.result),re},b=()=>{const h=/^[A-Za-z0-9]{2,}$/;let c=o.value.fluxNodeAlias,k=o.value.fluxNodeIP;if(!c)return t.$message.error(t.$t("message.enter_a_valid_zelnode_name")),!1;if(!k)return t.$message.error(t.$t("message.enter_a_valid_ip")),!1;if(c=c.replace(/\s/g,""),k=k.replace(/\s/g,""),c.length<2)return t.$message.error(t.$t("message.enter_a_valid_zelnode_name")),!1;if(!h.test(c))return t.$message.error(t.$t("message.special_char
--------------------------------------------------

[!] Найдено 'zelid' в файле: FluxNodesApp-CYp0vZaU.js
--------------------------------------------------
isible=!0},F=l=>l.fluxnodepk&&l.confirmations>=100&&!l.started&&l.status!==Z.STARTING&&l.status!==Z.STARTED&&l.status!==Z.CONFIRMED&&l.status!==Z.DOS,h=Q(()=>r.value.filter(l=>F(l))),c=l=>{const a=r.value.findIndex(_=>_.txhash===l.txhash&&_.outidx.toString()===l.outidx.toString());a>-1&&(r.value.splice(a,1),p.commit("setFluxNodes",JSON.parse(JSON.stringify(r.value))),(t.$isMobile||t.$isExtension)&&p.dispatch("saveFluxNodes"),t.$message.success(t.$t("message.fluxnode_deleted")))},k=Q(()=>p.state.zelid),V=j(""),B=l=>l.fluxnodepk,re=async l=>{if(!l.alias){t.$message.error(t.$t("message.enter_a_valid_zelnode_name"));return}try{const a={adminId:k.value.bitcoin,nodeKey:l.fluxnodepk,transactionOutput:l.txhash,transactionIndex:l.outidx,nodeName:l.alias},_=at.from(k.value.privkey,"hex"),M=JSON.stringify(a),E=i.value.bitcoin.messagePrefix,Y={headers:{"flux-signature":g.message.sign(M,_,!0,E).toString("base64")}},me=`${t.$localstore.get("proxyServer")}https://storage.runonflux.io/v1/node`,ge=await t.axios.post(me,a,Y);V.value=ge.data.data,L.addFluxNodeToStorageVisible=!0,t.$message.success(t.$t("message.flux_node_added_storage_success"))}catch(a){t.$log.error(a),t.$message.error(t.$t("message.error_adding_to_storage"))}},te=({dialog:l,value:a})=>{L[l]=a},oe=l=>{const[a,_]=l.split(":"),M=_?`${_-1}`:rt,E=`http://${a}:${M}`;p.dispatch("openLink",E)},O=l=>{P.value.elTable.toggleRowExpansion(l)},le=l=>{p.dispatch("openLink",l)},R=l=>{let a="CUMULUS";switch(l){case 1e3:a="CUMULUS";break;case
--------------------------------------------------

[!] Найдено 'privKeyWIF' в файле: Fusion-DBUYeGNB.js
--------------------------------------------------
ess")throw new Error(e.data.data.message||e.data.data);const n=e.data.data;let d,i=this.claimingAddress;if(this.selectedClaimingAddress===s.$t("message.custom_address"))F.isValidAddress(this.claimingAddress)?d=this.suppliedPrivateKey:d=this.suppliedPrivateKey.replace(/\s/g,"");else if(this.claimingAddress.startsWith("t1")||this.claimingAddress.startsWith("t3")){const b=this.coins.zelcash.addresses.find(g=>g.address===this.claimingAddress);if(!b)throw new Error(s.$t("message.signing_error"));d=b.privKeyWIF}else if(this.claimingAddress.startsWith("0x")){const b=this.coins.ethereum.addresses.find(g=>g.address===this.claimingAddress.toLowerCase());if(!b)throw new Error(s.$t("message.signing_error"));d=b.privKeyWIF}else if(this.claimingAddress.length>60||this.claimingAddress.includes(".")){let b=this.claimingAddress;this.claimingAddress.startsWith("k:")&&(b=b.substring(2));const g=this.coins.fluxkda.addresses.find(k=>k.address===b);if(!g)throw new Error(s.$t("message.signing_error"));d=g.privKeyWIF}else if(F.isValidAddress(this.claimingAddress)){const b=this.claimingAddress,g=this.coins.fluxalgo.addresses.find(k=>k.address===b);if(!g)throw new Error(s.$t("message.signing_error"));d=g.privKeyWIF}else if(this.claimingAddress.startsWith("T")&&this.claimingAddress.length<40){const b=this.coins.fluxtrx.addresses.find(g=>g.address===this.claimingAddress);if(!b)throw new Error(s.$t("message.signing_error"));d=b.privKeyWIF}else if(this.claimingAddress.startsWith("9")&&this.claimingAddress
--------------------------------------------------

[!] Найдено 'zelid' в файле: Fusion-DBUYeGNB.js
--------------------------------------------------
s:"selectIntro"},Pe={class:"hideMiniWidth"},Ke={class:"showMiniWidth"},Ne={class:"scrollQuickswap"},Ve={class:"coins"},Le={key:0,class:"logo"},De=["onClick"],Oe={class:"coin-container"},ze=["src","alt"],Re=["src"],Me=["onClick"],Ue={key:0,class:"deselectButton"},qe={class:"gridSelectAsset"},He={class:"coin-container"},je=["src","alt"],Ge=["src"],Ze={class:"text-right quickswapFiat"},Je={class:"quickswapAmount"},Xe={class:"quickswapText"},Qe={class:"quickswapButtons nonVisible"},Ye={key:1,class:"zelidCard"},si={key:0,class:"wyre"},ei={class:"wyreIntroPadding"},ii={class:"selectWithLabel"},ti={key:0},ni={key:0},ai={class:"selectWithLabel"},oi={key:0},li={key:0},ri={class:"inputWithLabel"},di={class:"inputWithLabel"},ci={key:0,class:"selectWithLabel"},hi={class:"amountsSection"},mi={class:"bold"},ui={class:"fusionNote"},gi={class:"selectWithLabel extraPadding"},fi={key:0},pi={class:"controlButtons"},bi={key:0,class:"nextButton"},vi={key:1,class:"nextButton"},yi={class:"disabled"},Ci={key:0,class:"wyre"},Ai={class:"wyreIntroPadding"},wi={class:"selectWithLabel"},_i={class:"selectWithLabel"},ki={class:"amountsSection"},xi={class:"bold"},$i={class:"fusionNote"},Wi={key:0},Si={class:"selectWithLabel extraPadding"},Ei={class:"selectWithLabel"},Ii={class:"controlButtons"},Fi={class:"previousButton"},Ti={class:"nextButton"},Bi={key:2,class:"zelidCard"},Pi={key:0,class:"wyre"},Ki={class:"wyreIntroPadding"},Ni={class:"selectWithLabel"},Vi={key:0},Li={key:0},Di={class:"selectWithLabel"},O
--------------------------------------------------

[!] Найдено 'privKeyWIF' в файле: IgraBridgeDialog-rcd4idpc.js
--------------------------------------------------
 e=A(this.amountSompi,this.igraL2Address,this.balanceSompi);if(!e.valid){this.$message.error(this.$t(`message.${e.error}`)),this.$store.commit("hardWorking",!1);return}let i;!f.$isMobile&&!f.$isExtension?i=`${window.__static}/libraries/kaspa/kaspa_bg.wasm`:f.$isMobile&&f.$cordova.device.platform==="Android"?i=`${f.$cordova.file.applicationDirectory}www/static/libraries/kaspa/kaspa_bg.wasm`:i="/static/libraries/kaspa/kaspa_bg.wasm",await Z(i);const s=this.coins.kaspa.addresses[this.activeWallet].privKeyWIF,o=this.coins.kaspa.addresses[this.activeWallet].address,r=new ge.PrivateKey(s),t=((this.coins.kaspa.feepolicy||{}).normal||0)/this.kaspaDecimals,{txId:a}=await me({senderAddress:o,privateKeyHex:r.toString(),l2Address:this.igraL2Address,amountSompi:this.amountSompi,fee:new F(t).toFixed(),kaspaWasmModule:j}),d=this.coins.kaspa.explorer[0];this.$store.commit("lastExplorerLightTx",{explorer:d,txid:a}),this.$store.commit("hardWorking",!1),this.closePopup(),this.$refs.transactionDialog.showPopup("",!1),setTimeout(()=>{this.$emit("bridge-finished")},5e3)}catch(e){this.$log.error(e),f.$notifyError(e);const i=e.message||String(e);this.$message.error(`${this.$t("message.igra_bridge_error")}: ${i}`),this.$store.commit("hardWorking",!1)}},onTransactionDialogClose(){this.$store.commit("cleanlighttx")},roundInput(e,i){const s=10**i,o=Math.round(e*s)/s;if(e>0){const r=o.toFixed(i).replace(/0+$/,"");return r.charAt(r.length-1)==="."||r.charAt(r.length-1)===","?r.slice(0,-1):r}return e}}},pe
--------------------------------------------------

[!] Найдено 'privKeyWIF' в файле: ImportCosmosToken-DzV6QEi1.js
--------------------------------------------------
tract="",C("update:modelValue",!1),C("close")},V=()=>{const{contract:t}=r.value;return t?!0:(d.$message.error(d.$t("message.missing_token_specs")),!1)},D=async()=>{if(!V())return;const{contract:t,name:e,unit:i}=r.value;try{const s=await U({contractAddress:t,chain:p.chainId});if(!(s&&+s.amount>0))throw new Error("Contract/Denom not listed");const o=E({contractAddress:s.denom,tokenName:e,tokenSymbol:i,type:p.chainId});for(const[g,k]of o.addresses.entries())k.address=v.value.addresses[g].address,k.privKeyWIF=v.value.addresses[g].privKeyWIF,k.publicKey=v.value.addresses[g].publicKey;a.commit("importTokensIntoCoins",[o]),a.commit("saveImportedCosmosTokensToAccount",JSON.parse(JSON.stringify({contract:o.contractAddress,name:e,unit:i,type:p.chainId}))),setTimeout(()=>{f()},1e3),a.commit("addCoin",{coin:o.coin}),a.dispatch("saveAccount")}catch(s){d.$message.error(`Retriving contract info was not possible. ${s.message}`),d.$log.error(s)}};return(t,e)=>{const i=b("ZelButton"),s=b("ElDialog");return A(),B(s,{"model-value":c.modelValue,title:t.$t(N(K).CosmosUi[c.chainId].importDialogTitle),width:"80%","append-to-body":"",onClose:e[5]||(e[5]=o=>f())},{footer:u(()=>[I(i,{round:"",onClick:e[3]||(e[3]=o=>f())},{default:u(()=>[l(m(t.$t("message.cancel")),1)]),_:1}),I(i,{round:"",type:"primary",onClick:e[4]||(e[4]=o=>D())},{default:u(()=>[l(m(t.$t("message.import")),1)]),_:1})]),default:u(()=>[n("p",null,[l(m(t.$t("message.insert_token_name"))+" ",1),e[6]||(e[6]=n("br",null,null,-1)),y(n("inpu
--------------------------------------------------

[!] Найдено 'privKeyWIF' в файле: ImportEthLikeToken-CjNv76sT.js
--------------------------------------------------
!1),y("close")},S=()=>{const{contract:t,name:e,unit:i}=o.value;return!t||!e||!i?(s.$message.error(s.$t("message.missing_token_specs")),!1):!0},L=async()=>{if(!S())return;const{contract:t,name:e,unit:i}=o.value;try{const n=await new F(p.chainId,s.$localstore.get("proxyServer")+E.value).getContractDecimals(t),k=J.generateImportedTokenData({contractAddress:t,tokenName:e,tokenSymbol:i,tokenDecimals:n,chainId:p.chainId});for(const[I,T]of k.addresses.entries())T.address=u.value.addresses[I].address,T.privKeyWIF=u.value.addresses[I].privKeyWIF;r.commit("importEthLikeTokens",[k]),r.commit("saveImportedEthLikeTokensToAccount",JSON.parse(JSON.stringify({...o.value,decimals:n,type:p.chainId}))),setTimeout(()=>{g()},1e3),r.commit("addCoin",{coin:k.coin}),r.dispatch("saveAccount")}catch(d){s.$message.error(s.$t("Retriving contract info was not possible. Please check contract address and blockchain.")),s.$log.error(d)}};return(t,e)=>{const i=b("ZelButton"),d=b("ElDialog");return w(),A(d,{"model-value":v.modelValue,title:t.$t(B(O)[v.chainId].importDialogTitle),width:"80%","append-to-body":"",onClose:e[5]||(e[5]=n=>g())},{footer:c(()=>[C(i,{round:"",onClick:e[3]||(e[3]=n=>g())},{default:c(()=>[l(m(t.$t("message.cancel")),1)]),_:1}),C(i,{round:"",type:"primary",onClick:e[4]||(e[4]=n=>L())},{default:c(()=>[l(m(t.$t("message.import")),1)]),_:1})]),default:c(()=>[a("p",null,[l(m(t.$t("message.insert_token_name"))+" ",1),e[6]||(e[6]=a("br",null,null,-1)),$(a("input",{"onUpdate:modelValue":e[0]||(
--------------------------------------------------

[!] Найдено 'privKeyWIF' в файле: ImportTokenWithType-ZUCrCsnb.js
--------------------------------------------------
ject.values(i.state.coins).find(e=>e.coinType==="native"&&e.type===p.chainId)),s=V({contract:""}),c=()=>{s.value.contract="",T("update:modelValue",!1),T("close")},C=()=>{const{contract:e}=s.value;return e?!0:(a.$message.error(a.$t("message.missing_token_specs")),!1)},b=async()=>{if(!C())return;const{contract:e}=s.value;try{const t=a.$localstore.get("proxyServer"),o=await W(e,p.chainId,t),{name:d,unit:r,decimals:h}=o;for(const[u,v]of o.addresses.entries())v.address=l.value.addresses[u].address,v.privKeyWIF=l.value.addresses[u].privKeyWIF,v.publicKey=l.value.addresses[u].publicKey;i.commit("importTokensIntoCoins",[o]),i.commit("saveImportedTokensWithTypeToAccount",JSON.parse(JSON.stringify({contract:e,name:d,unit:r,decimals:h,type:p.chainId}))),setTimeout(()=>{c()},1e3),i.commit("addCoin",{coin:o.coin}),i.dispatch("saveAccount")}catch(t){a.$message.error(`Retriving contract info was not possible. ${t.message}`),a.$log.error(t)}};return(e,t)=>{const o=$("ZelButton"),d=$("ElDialog");return B(),S(d,{"model-value":m.modelValue,title:e.$t(A(K)[m.chainId].importDialogTitle),width:"80%","append-to-body":"",onClose:t[3]||(t[3]=r=>c())},{footer:n(()=>[k(o,{round:"",onClick:t[1]||(t[1]=r=>c())},{default:n(()=>[g(y(e.$t("message.cancel")),1)]),_:1}),k(o,{round:"",type:"primary",onClick:t[2]||(t[2]=r=>b())},{default:n(()=>[g(y(e.$t("message.import")),1)]),_:1})]),default:n(()=>[f("p",null,[g(y(e.$t("message.insert_contract_address"))+" ",1),t[4]||(t[4]=f("br",null,null,-1)),N(f("input",{"o
--------------------------------------------------

[!] Найдено 'privKeyWIF' в файле: ImportTonToken-Cihbat6C.js
--------------------------------------------------
ative"&&e.type===l.chainId)),a=V({contract:""}),d=()=>{a.value.contract="",k("update:modelValue",!1),k("close")},b=()=>{const{contract:e}=a.value;return e?!0:(i.$message.error(i.$t("message.missing_token_specs")),!1)},C=async()=>{if(!b())return;const{contract:e}=a.value;try{const{name:t,symbol:s,decimals:n}=await J({contractAddress:e}),o=O({contractAddress:e,tokenName:t,tokenSymbol:s,tokenDecimals:n,type:l.chainId});for(const[u,v]of o.addresses.entries())v.address=c.value.addresses[u].address,v.privKeyWIF=c.value.addresses[u].privKeyWIF,v.publicKey=c.value.addresses[u].publicKey;r.commit("importTokensIntoCoins",[o]),r.commit("saveImportedTonTokensToAccount",JSON.parse(JSON.stringify({contract:e,name:t,unit:s,decimals:n,type:l.chainId}))),setTimeout(()=>{d()},1e3),r.commit("addCoin",{coin:o.coin}),r.dispatch("saveAccount")}catch(t){i.$message.error(`Retriving contract info was not possible. ${t.message}`),i.$log.error(t)}};return(e,t)=>{const s=T("ZelButton"),n=T("ElDialog");return h(),B(n,{"model-value":p.modelValue,title:e.$t(w(K).TonUi[p.chainId].importDialogTitle),width:"80%","append-to-body":"",onClose:t[3]||(t[3]=o=>d())},{footer:m(()=>[$(s,{round:"",onClick:t[1]||(t[1]=o=>d())},{default:m(()=>[g(y(e.$t("message.cancel")),1)]),_:1}),$(s,{round:"",type:"primary",onClick:t[2]||(t[2]=o=>C())},{default:m(()=>[g(y(e.$t("message.import")),1)]),_:1})]),default:m(()=>[f("p",null,[g(y(e.$t("message.insert_contract_address"))+" ",1),t[4]||(t[4]=f("br",null,null,-1)),N(f("input",{"
--------------------------------------------------

[!] Найдено 'privKeyWIF' в файле: index-817yN7Xf.js
--------------------------------------------------
enerateAddress$5({privateKey:e}){const{publicKey:t,secretKey:jn}=pact$1.crypto.restoreKeyPairFromSecretKey(e);return{publicKey:t,privateKey:jn,kAccount:`k:${t}`}}function generateImportedTokenData$7({contractAddress:e,tokenName:t,tokenSymbol:jn,tokenDecimals:Yn,network:Po}){return{coin:`${extras$2.kadena.tokenKeyPrefix}${e}`,name:`${t} ${extras$2.kadena.tokenNamePostfix}`,uri:[t.split(" ").join("").toLowerCase(),jn.toLowerCase()],addresses:Array(12).fill(void 0).map(()=>({address:"",accounts:[],privKeyWIF:"",confirmed:{},unconfirmed:{},transactions:{}})),unit:jn,type:"kadena",coinType:"token",chainIDs:new Array(20).fill(void 0).map((Vo,jc)=>`${jc}`),logolink:"@/assets/logos/NoImage.svg",fee:extras$2.kadena.fee,feepolicy:{...extras$2.kadena.feepolicy},color:"#ffffff",namespace:e,decimals:Number(Yn),chain:Po,explorer:backends.kadena.explorer,node:backends.kadena.node,api:backends.kadena.api}}function generateImportedTokenDataPopulated({contractAddress:e,tokenName:t,tokenSymbol:jn,tokenDecimals:Yn,network:Po,privateKeys:qo}){const Vo=generateImportedTokenData$7({contractAddress:e,tokenName:t,tokenSymbol:jn,tokenDecimals:Yn,network:Po});for(const jc of qo)if(jc){const{publicKey:Mc,kAccount:gd,privateKey:Ad}=generateAddress$5({privateKey:jc}),yd={address:Mc,accounts:[gd,Mc],privKeyWIF:Ad,confirmed:{[Mc]:{},[gd]:{}},unconfirmed:{[Mc]:{},[gd]:{}},transactions:{}};for(const Bd of Vo.chainIDs)yd.confirmed[Mc][Bd]=0,yd.confirmed[gd][Bd]=0,yd.unconfirmed[Mc][Bd]=0,yd.unconfirmed[gd][Bd]
--------------------------------------------------

[!] Найдено 'zelid' в файле: index-817yN7Xf.js
--------------------------------------------------
try{const qo=`${BASE_PATH}${t}`,{signature:Vo,timestamp:jc}=signData(e,qo,jn,Yn,Po),Mc=`${BASE_URL}${t}`,gd={method:Po,url:Mc,headers:{"Content-Type":"application/json",Authorization:`Bearer ${Vo}`,"X-Flux-ID":jn,"X-Timestamp":jc}};return["POST","PUT","PATCH","DELETE"].includes(Po.toUpperCase())&&(gd.data={fluxId:jn,timestamp:jc,data:Yn,signature:Vo}),(await axios.request(gd)).data}catch(qo){return console.error(qo),null}}function createNotificationsApi(e){const t=async(yd,Bd,Cd="POST")=>{const{zelid:vd}=e.state;if(!vd||!vd.privkey||!vd.bitcoin)throw new Error("User not logged in or missing credentials");return sendRequest(vd.privkey,yd,vd.bitcoin,Bd,Cd)};return{sendApiRequest:t,getSettings:async()=>t("/settings",void 0,"POST"),getLoginReportingStatus:async()=>t("/settings/login-reporting-status",void 0,"POST"),updateSettings:async yd=>t("/settings/update",yd,"POST"),reportLogin:async yd=>t("/login-report",yd,"POST"),getLoginHistory:async()=>t("/login-history",void 0,"POST"),getKnownDevices:async()=>t("/known-devices",void 0,"POST"),addToKnownDevices:async yd=>{let Bd=await t("/known-devices/authorize",yd,"POST");return(!Bd||Bd.status!=="success")&&(Bd=await t("/known-devices",yd,"POST")),Bd},removeDevice:async yd=>t(`/known-devices/${yd}`,{},"DELETE"),deleteAllData:async()=>t("/disconnect",{},"POST")}}const useNotificationsStore=e=>{const{getSettings:t,getLoginReportingStatus:jn,updateSettings:Yn,reportLogin:Po,getLoginHistory:qo,getKnownDevices:Vo,addToKnownDevices:jc,remov
--------------------------------------------------

[!] Найдено 'login-reporting-status' в файле: index-817yN7Xf.js
--------------------------------------------------
UpperCase())&&(gd.data={fluxId:jn,timestamp:jc,data:Yn,signature:Vo}),(await axios.request(gd)).data}catch(qo){return console.error(qo),null}}function createNotificationsApi(e){const t=async(yd,Bd,Cd="POST")=>{const{zelid:vd}=e.state;if(!vd||!vd.privkey||!vd.bitcoin)throw new Error("User not logged in or missing credentials");return sendRequest(vd.privkey,yd,vd.bitcoin,Bd,Cd)};return{sendApiRequest:t,getSettings:async()=>t("/settings",void 0,"POST"),getLoginReportingStatus:async()=>t("/settings/login-reporting-status",void 0,"POST"),updateSettings:async yd=>t("/settings/update",yd,"POST"),reportLogin:async yd=>t("/login-report",yd,"POST"),getLoginHistory:async()=>t("/login-history",void 0,"POST"),getKnownDevices:async()=>t("/known-devices",void 0,"POST"),addToKnownDevices:async yd=>{let Bd=await t("/known-devices/authorize",yd,"POST");return(!Bd||Bd.status!=="success")&&(Bd=await t("/known-devices",yd,"POST")),Bd},removeDevice:async yd=>t(`/known-devices/${yd}`,{},"DELETE"),deleteAllData:async()=>t("/disconnect",{},"POST")}}const useNotificationsStore=e=>{const{getSettings:t,getLoginReportingStatus:jn,updateSettings:Yn,reportLogin:Po,getLoginHistory:qo,getKnownDevices:Vo,addToKnownDevices:jc,removeDevice:Mc,deleteAllData:gd}=createNotificationsApi(e),Ad=ref({email:null,emailVerified:!1,securityNotifications:!1,loginTracking:!1,zelcoreNews:!1}),yd=ref({loginReportingEnabled:!1,emailConfigured:!1,emailVerified:!1}),Bd=ref([]),Cd=ref(!1),vd=ref(null),kd=computed(()=>e.state.logi
--------------------------------------------------

[!] Найдено 'zelid' в файле: index-DcgmqKag.js
--------------------------------------------------
sitionRewards(t,n){return this.provider.getPositionRewards(t,n)}async getValidators(){return this.validatorService.getValidators()}async getValidator(t){return this.validatorService.getValidator(t)}async getValidatorDirect(t){return this.validatorService.getValidatorDirect(t)}async getNetworkInfo(){return this.validatorService.getNetworkInfo()}async getTransactionHistory(t){return this.historyService.getTransactionHistory(t)}}function ur(e){return e.substring(e.length-13)}function bo(e){return[`zelid=${encodeURIComponent(e.zelId)}`,`signature=${encodeURIComponent(e.signature)}`,`loginPhrase=${encodeURIComponent(e.loginPhrase)}`].join("&")}class go{baseUrl;fluxIdBaseUrl;platform;cache=new Map;constructor(t=ao,n=io,r="macos"){this.baseUrl=t,this.fluxIdBaseUrl=n,this.platform=r}getHeaders(){return{...oo,platform:this.platform}}getAuthHeaders(t){return{...this.getHeaders(),zelidauth:bo(t)}}getCached(t,n){const r=this.cache.get(t);return r&&Date.now()<r.expiry?r.data:(this.cache.delete(t),null)}setCache(t,n,r){this.cache.set(t,{data:n,expiry:Date.now()+r})}async fetchJson(t,n){const r=await fetch(t,n);if(!r.ok)throw new j("STAKING_API_ERROR",`Titan API error: ${r.status} ${r.statusText}`);return r.json()}async fetchText(t,n){const r=await fetch(t,n);if(!r.ok)throw new j("STAKING_API_ERROR",`Titan API error: ${r.status} ${r.statusText}`);return r.text()}async getConfig(){const t=this.getCached("config",3e5);if(t)return t;const n=await this.fetchJson(`${this.baseUrl}/config`,{header
--------------------------------------------------

[!] Найдено 'privKeyWIF' в файле: KaspaTokenDialog-BC3PKcrS.js
--------------------------------------------------
plex_api_error"));return}const{decimals:f}=this.importToken;if(Object.keys(this.coins).find(i=>this.coins[i].contractAddress?+this.coins[i].contractAddress===e:+this.coins[i].contractAddress===e)){this.$message.error(this.$t("message.specs_exists"));return}const s={coin:`kaspa${e}`,name:`${o} KAS`,uri:[o.split(" ").join("").toLowerCase(),e.toLowerCase()],slip:111111,pubKeyHash:"1c",scriptHash:"28",wif:"80",addresses:new Array(12).fill().map((i,m)=>({address:this.coins.kaspa.addresses[m].address,privKeyWIF:this.coins.kaspa.addresses[m].privKeyWIF,confirmed:0,unconfirmed:0,transactions:[]})),unit:e,type:"kaspa",coinType:"token",logolink:"@/assets/logos/NoImage.svg",fee:1e-4,feepolicy:{economy:1,normal:3,fast:10},contractAddress:e,color:"#ffffff",decimals:Number(f),explorer:l.kaspa.explorer,node:l.kaspa.node,api:l.kaspa.tokensApi};this.$store.commit("importTokensIntoCoins",[s]),this.$store.commit("saveImportedTokensWithTypeToAccount",JSON.parse(JSON.stringify({contract:s.contractAddress,name:o,unit:e,decimals:s.decimals,type:s.type}))),this.showPopupDialog=!1,setTimeout(()=>{t.importToken.name="",t.importToken.decimals=8,t.importToken.unit="",t.importToken.contract=""}),this.$store.commit("addCoin",{coin:`kaspa${e}`}),this.$store.dispatch("saveAccount"),this.$store.commit("hardWorking",!1)}}},_=["placeholder"],D=["placeholder"];function K(t,o,e,f,r,p){const s=h("ZelButton"),i=h("ElDialog"),m=h("ZelSpinner");return C(),A(v,null,[c(i,{"model-value":r.showPopupDialog,title:t.$t("me
--------------------------------------------------

[!] Найдено 'privKeyWIF' в файле: KdaTokenDialog-x2Tszs5i.js
--------------------------------------------------
rtToken.unit=""})},importKDATokenCoinInformation(){const o=this,{contract:e}=this.importToken,{name:d}=this.importToken,{unit:c}=this.importToken,{decimals:t}=this.importToken;if(!e||!d||!c||!t){o.$message.error(o.$t("message.missing_token_specs"));return}if(Object.keys(this.coins).find(m=>this.coins[m].namespace?this.coins[m].namespace.toLowerCase()===e.toLowerCase():this.coins[m].namespace===e)){o.$message.error(o.$t("message.specs_exists"));return}const T=this.coins.kadena.addresses.map(m=>m.privKeyWIF),i=D.generateImportedTokenDataPopulated({contractAddress:e,tokenName:d,tokenSymbol:c,tokenDecimals:t,network:this.coins.kadena.chain,privateKeys:T});this.$store.commit("importKDATokens",[i]),this.$store.commit("saveKDATokensToAccount",JSON.parse(JSON.stringify(this.importToken))),this.showPopupDialog=!1,setTimeout(()=>{o.importToken.contract="",o.importToken.name="",o.importToken.decimals=12,o.importToken.unit=""}),this.$store.commit("addCoin",{coin:i.coin}),this.$store.dispatch("saveAccount")}}},b=["placeholder"],P=["placeholder"],A=["placeholder"],K=["placeholder"];function y(o,e,d,c,t,p){const k=f("ZelButton"),T=f("ElDialog");return $(),v(T,{"model-value":t.showPopupDialog,title:o.$t("message.import_kda_token"),width:"80%","append-to-body":"",onClose:e[5]||(e[5]=i=>p.closePopup())},{footer:l(()=>[g(k,{round:"",onClick:e[4]||(e[4]=i=>p.closePopup())},{default:l(()=>[s(r(o.$t("message.cancel")),1)]),_:1}),g(k,{round:"",type:"primary",onClick:p.importKDATokenCoinInformation}
--------------------------------------------------

[!] Найдено 'privKeyWIF' в файле: MergeSolanaAccountDialog-TSLo3UXs.js
--------------------------------------------------
dress),d=new r.PublicKey(this.coins.solana.addresses[this.activeWallet].address),{decimals:h}=this.coins[this.activeCoin];this.solanaSPLBalances.forEach(g=>{if(g.account!==this.coins[this.activeCoin].addresses[this.activeWallet].address){const _=g.balance*10**h,w=W(g.account,c,i,d,_,h);a.add(w);const $=T(g.account,d,d);a.add($)}});const b=r.ComputeBudgetProgram.setComputeUnitPrice({microLamports:6e4});a.add(b);const C=r.Keypair.fromSecretKey(A.from(this.coins.solana.addresses[this.activeWallet].privKeyWIF,"hex"));a.sign(C);const y=a.serialize(),k=await l.sendRawTransaction(y,{preflightCommitment:"confirmed"});console.log(k);const n=this;setTimeout(()=>{n.solanaBalAccounts()},5e3),setTimeout(()=>{t?n.$message.success(n.$t("message.wrapping_success")):n.$message.success(n.$t("message.merge_success"))},8e3),setTimeout(()=>{n.$emit("merging-finished")},1e4),setTimeout(()=>{n.$store.commit("hardWorking",!1),n.solanaBalAccounts()},12e3),this.closePopup()}catch(e){this.$store.commit("hardWorking",!1),this.$log.error(e),this.$message.error(e.message||e)}},async solanaBalAccounts(){try{if(this.activeCoin==="solana")return;const t=this.loggedaccount[0].apiService.solana||this.coins.solana.api[0],{address:e}=this.coins.solana.addresses[this.activeWallet],{mint:s}=this.coins[this.activeCoin],l=this.$localstore.get("proxyServer")+t,m={jsonrpc:"2.0",id:Math.random().toString(36).slice(2)+Math.random().toString(36).slice(2),method:"getTokenAccountsByOwner",params:[e,{mint:s},{encoding:"json
--------------------------------------------------

[!] Найдено 'privKeyWIF' в файле: NftSendSection-C1EOzDGW.js
--------------------------------------------------
{pe.$log.error("Error while sending tx"),pe.$log.error(l);const a=q6(t,aa[e].node);throw a&&await Pw(e,r,a),new lb(l)}}async function JB(e,r,t,l,a,n,i,s,c,o=aa[e].node[0]){const d=new nb(e,pe.$localstore.get("proxyServer")+o),p=ig.getters.coins[aa[e].feeCoin],u={gasLimit:s,gasPrice:Number(c*1e9),from:a,value:0,to:t,isTokenTransfer:!0,tokenData:{contractAddress:t,decimals:0,value:1,to:n,from:a,tokenId:l,tokenStandard:r}},{signedTxHex:m}=await d.signTransaction({txData:u,privateKey:p.addresses[i].privKeyWIF});return console.log(`Serialized tx: ${m}`),await Pw(e,m)}async function YB(e){const{nftStoreState:r}=Rm(),t=r.nfts[e.nftId],l=(await U6(aa[t.blockchain].feeCoin,e.addressTo)).address;if(l.length!==42||l[0]!=="0"||l[1]!=="x")throw new F6;if(!QB(t.blockchain,t.walletId,e.fee,e.gasPrice))throw new N6;if(!ZB.includes(t.coinType))throw new ab;if(!await bw(t.blockchain,t.coinType,t.contractAddress,t.tokenId,t.wallet))throw new yw;const a=await JB(t.blockchain,t.coinType,t.contractAddress,t.tokenId,t.wallet,l,t.walletId,e.fee,e.gasPrice);return console.log(`Txid: ${a}`),a}const Sw=e=>({__option:"Some",value:e}),C6=()=>({__option:"None"}),XB=e=>e&&typeof e=="object"&&"__option"in e&&(e.__option==="Some"&&"value"in e||e.__option==="None"),Ab=e=>e.__option==="Some",$B=e=>e!==null?Sw(e):C6();let eV=class extends Error{name="InvalidBaseStringError";constructor(r,t,l){const a=`Expected a string of base ${t}, got [${r}].`;super(a),this.cause=l}};const rV=e=>{const r=e.length,t=BigInt(r);
--------------------------------------------------

[!] Найдено 'privKeyWIF' в файле: OmniTokenDialog-JgduEw7y.js
--------------------------------------------------
or(e.$t("message.missing_token_specs"));return}if(Object.keys(this.coins).find(i=>Number(this.coins[i].tokenNumber)===Number(o))){e.$message.error(e.$t("message.specs_exists"));return}const f={coin:`omni${o}`,name:`${m} OMNI`,uri:[m.split(" ").join("").toLowerCase(),p.toLowerCase()],pubKeyHash:"00",scriptHash:"05",normalAddress:"1",scriptAddress:"3",normalAddressB:"1",scriptAddressB:"3",wif:"80",slip:200,addresses:new Array(12).fill().map((i,T)=>({address:this.coins.bitcoin.addresses[T].address,privKeyWIF:this.coins.bitcoin.addresses[T].privKeyWIF,confirmed:0,unconfirmed:0,transactions:[]})),unit:p,type:"omni",coinType:"token",logolink:"@/assets/logos/NoImage.svg",fee:226e-7,feepolicy:{economy:22,normal:30,fast:55},color:"#ffffff",decimals:Number(t),tokenNumber:Number(o),explorer:a.omni.explorer,node:a.omni.node,api:a.omni.api,blockbook:a.omni.blockbook};this.$store.commit("importOMNITokens",[f]),this.$store.commit("saveOMNITokensToAccount",JSON.parse(JSON.stringify(this.importToken))),this.showPopupDialog=!1,setTimeout(()=>{e.importToken.contract="",e.importToken.name="",e.importToken.decimals=8,e.importToken.unit=""}),this.$store.commit("addCoin",{coin:`omni${o}`}),this.$store.dispatch("saveAccount")}}},v=["placeholder"],w=["placeholder"],D=["placeholder"],I=["placeholder"];function O(e,o,m,p,t,l){const k=g("ZelButton"),f=g("ElDialog");return y(),C(f,{"model-value":t.showPopupDialog,title:e.$t("message.import_omni_token"),width:"80%","append-to-body":"",onClose:o[5]||(o[5]=
--------------------------------------------------

[!] Найдено 'zelid' в файле: providers-B2422CBN.js
--------------------------------------------------
ze({AUTH:"/auth",CHAT:"/chat",IMAGE:"/image"});async function*Z(f){const l=new TextDecoder("utf-8"),o=f.getReader();let s="";for(;;)try{const{value:m,done:i}=await o.read();if(i)break;s+=l.decode(m,{stream:!0});const y=s.split(`
`);s=y.pop();for(const h of y)if(h.trim()){const n=h.replace("data: ","");yield JSON.parse(n)}}catch{break}}const T=f=>new ReadableStream({start(o){const s=new TextEncoder;o.enqueue(s.encode(`${JSON.stringify(f)}
`)),o.close()}});function J(){const f=$(),l=C(()=>f.state.zelid),o=C(()=>f.state.fluxAI.FLUXTOKEN),s=C(()=>{try{return B(o.value)}catch(r){return console.log(r),null}}),m=(r,e,g,c,d="POST")=>{const p=Date.now(),u=`${d}|${e}|${g}|${p}|${JSON.stringify(c||{})}`;return{signature:P.message.sign(u,L.from(r,"hex"),!0,`Bitcoin Signed Message:
`).toString("base64"),timestamp:p}};return{isTokenExpiring:()=>{const e=Date.now();return!!(s.value===null||s.value&&s.value.exp*1e3-6e4<e)},runOnFluxConnect:async r=>{console.log("Running runOnFluxConnect");const e=l.value.bitcoin,g={fluxId:e,expirationDays:r},c="/connect",{signature:d,timestamp:p}=m(l.value.privkey,c,e,g);try{const u=await x.axios.post(`${S.ZELCOREAPI}${w.AUTH}${c}`,{signature:d,timestamp:p,data:g,fluxId:e},{headers:{"Content-Type":"application/json"}});if(u&&u.data&&u.data.status==="success")return u.data.data}catch(u){console.log("error"),console.log(u)}return null},runOnFluxChatCompletion:async(r,e,g)=>{const c=new AbortController,{signal:d}=c;g(c);const p={model:r,chat:e},u="/generate",I
--------------------------------------------------

[!] Найдено 'privKeyWIF' в файле: ReceiverSPLDialog-2lx1IQQZ.js
--------------------------------------------------
P=new s.PublicKey(this.coins.solana.addresses[this.activeWallet].address),l=R(P,v,b,a);console.log(l);const c=new s.PublicKey(this.coins.solana.addresses[this.activeWallet].address),y=await i.getLatestBlockhash("finalized"),m=new s.Transaction({blockhash:y.blockhash,feePayer:c,lastValidBlockHeight:y.lastValidBlockHeight});m.add(l);const _=s.ComputeBudgetProgram.setComputeUnitPrice({microLamports:6e4});m.add(_);const w=s.Keypair.fromSecretKey($.from(this.coins.solana.addresses[this.activeWallet].privKeyWIF,"hex"));m.sign(w);const C=m.serialize(),k=await i.sendRawTransaction(C,{preflightCommitment:"confirmed"});console.log(k);const p=this;setTimeout(()=>{p.$message.success(p.$t("message.spl_creation_success"))},8e3),setTimeout(()=>{p.$store.commit("hardWorking",!1),p.closePopup()},12e3)}catch(t){this.$store.commit("hardWorking",!1),this.$log.error(t),this.$message.error(t.message||t)}}}},W={class:"gradientButton biggestbutton"};function E(t,e,i,f,a,n){const v=u("Icon"),b=u("el-popconfirm"),P=u("ZelButton"),l=u("ElDialog");return I(),K(l,{"model-value":a.showPopupDialog,title:t.$t("message.create_receiver_spl"),width:"80%","append-to-body":"",onClose:e[2]||(e[2]=c=>n.closePopup())},{footer:d(()=>[h(P,{round:"",onClick:e[1]||(e[1]=c=>n.closePopup())},{default:d(()=>[g(r(t.$t("message.close")),1)]),_:1})]),default:d(()=>[h(v,{icon:"exclamation-triangle"}),g(" "+r(t.$t("message.receiver_spl_not_exist",{name:t.coins[i.activeCoin].name,unit:t.coins[i.activeCoin].unit}))+" ",1),e[5]||
--------------------------------------------------

[!] Найдено 'privKeyWIF' в файле: SecurityApp-Dm58R19h.js
--------------------------------------------------
ID:!1,wallet:0,coin:"zelcash",message:"",signature:""},o=L({...S}),v=j(()=>o.value.useFluxID?n.value.bitcoin:e.value[o.value.coin].addresses[o.value.wallet].address),{copyToClipboard:i}=ve(),f=async t=>{},y=()=>{o.value={...S}},A=()=>{M.value.activeComponent="main"},I=()=>{o.value.signature="",o.value.message=""};Q(()=>{y()});const $=()=>{_.value.showPopup()},T=async()=>{try{if(o.value.message.length>0){const t={...o.value};if(t.useFluxID?(t.coin="bitcoin",t.wallet=0,t.address=n.value.bitcoin,t.privKeyWIF=n.value.privkey):(t.address=e.value[t.coin].addresses[t.wallet].address,t.privKeyWIF=e.value[t.coin].addresses[t.wallet].privKeyWIF),e.value[t.coin].family==="ethlike"){const a=B.value.nodeService.ethereum||e.value.ethereum.node[0],D=new ge(e.value[t.coin].type,m.$localstore.get("proxyServer")+a).signMessage({message:t.message,privateKey:t.privKeyWIF});console.log(D),o.value.signature=D.signature,m.$message.success(m.$t("message.message_signed"))}else if(e.value[t.coin].type==="tron"){const a=new Ze({fullHost:"http://127.0.0.1:9090",headers:{"TRON-PRO-API-KEY":"bad-api-key"}}),Z=t.privKeyWIF,D=a.toHex(t.message),x=await a.trx.sign(D,Z);console.log(x),o.value.signature=x,m.$message.success(m.$t("message.message_signed"))}else if(e.value[t.coin].type==="solana"){const a=t.privKeyWIF,D=new TextEncoder().encode(t.message),x=u.Keypair.fromSecretKey(N.from(a,"hex")),z=g.sign.detached(D,x.secretKey),W=h.encode(z);o.value.signature=W,m.$message.success(m.$t("message.message_signed")
--------------------------------------------------

[!] Найдено 'zelid' в файле: SecurityApp-Dm58R19h.js
--------------------------------------------------
i[4]||(i[4]=I=>S())},{default:r(()=>[F(d(v.$t("message.back")),1)]),_:1}),l(A,{type:"primary",round:"",disabled:c(g),onClick:i[5]||(i[5]=I=>o())},{default:r(()=>[F(d(c(u)?v.$t("message.disable_easy_login"):v.$t("message.set_up_easy_login")),1)]),_:1},8,["disabled"])])])}}},es={class:"security__app_main"},ss=["checked"],ts={class:"security__d2fa_area-item"},as={__name:"SignMessage",setup(K){const u=fe,g=he||ke,h=$e||be,k=we||Ce,_=L(null),M=O("state"),w=pe(),e=j(()=>w.state.coins),n=j(()=>w.state.zelid),B=j(()=>w.state.loggedaccount[0]),S={useFluxID:!1,wallet:0,coin:"zelcash",message:"",signature:""},o=L({...S}),v=j(()=>o.value.useFluxID?n.value.bitcoin:e.value[o.value.coin].addresses[o.value.wallet].address),{copyToClipboard:i}=ve(),f=async t=>{},y=()=>{o.value={...S}},A=()=>{M.value.activeComponent="main"},I=()=>{o.value.signature="",o.value.message=""};Q(()=>{y()});const $=()=>{_.value.showPopup()},T=async()=>{try{if(o.value.message.length>0){const t={...o.value};if(t.useFluxID?(t.coin="bitcoin",t.wallet=0,t.address=n.value.bitcoin,t.privKeyWIF=n.value.privkey):(t.address=e.value[t.coin].addresses[t.wallet].address,t.privKeyWIF=e.value[t.coin].addresses[t.wallet].privKeyWIF),e.value[t.coin].family==="ethlike"){const a=B.value.nodeService.ethereum||e.value.ethereum.node[0],D=new ge(e.value[t.coin].type,m.$localstore.get("proxyServer")+a).signMessage({message:t.message,privateKey:t.privKeyWIF});console.log(D),o.value.signature=D.signature,m.$message.success(m.$t("message.messa
--------------------------------------------------

[!] Найдено 'privKeyWIF' в файле: SolTokenDialog-CYliW2DW.js
--------------------------------------------------
p.PublicKey(this.coins.solana.addresses[i].address).toBuffer(),$.toBuffer(),A.toBuffer()],S=await p.PublicKey.findProgramAddress(D,w);a[`solAddr${i}`]=S[0].toBase58()}else a[`solAddr${i}`]=this.coins.solana.addresses[i].address.includes(P.NOT_SUPPORTED)?P.NOT_SUPPORTED:""}catch{e.$message.error(e.$t("message.invalid_mint"));return}const n={coin:`sol${o}`,name:`${d} SPL`,uri:[d.split(" ").join("").toLowerCase(),u.toLowerCase()],addresses:new Array(12).fill().map((r,f)=>({address:a[`solAddr${f}`],privKeyWIF:this.coins.solana.addresses[f].privKeyWIF,confirmed:0,unconfirmed:0,transactions:[]})),mint:o,unit:u,type:"solana",coinType:"token",logolink:"@/assets/logos/NoImage.svg",fee:17e-6,feepolicy:{economy:1,normal:1,fast:1},color:"#ffffff",decimals:Number(s),explorer:y.solana.explorer,node:y.solana.node,api:y.solana.api};this.$store.commit("importSOLTokens",[n]),this.$store.commit("saveSOLTokensToAccount",JSON.parse(JSON.stringify(this.importToken))),this.showPopupDialog=!1,setTimeout(()=>{e.importToken.contract="",e.importToken.name="",e.importToken.decimals=9,e.importToken.unit=""}),this.$store.commit("addCoin",{coin:`sol${o}`}),this.$store.dispatch("saveAccount")}}},K=["placeholder"],V=["placeholder"],I=["placeholder"],U=["placeholder"];function W(e,o,d,u,s,c){const h=b("ZelButton"),a=b("ElDialog");return O(),L(a,{"model-value":s.showPopupDialog,title:e.$t("message.import_sol_token"),width:"80%","append-to-body":"",onClose:o[5]||(o[5]=n=>c.closePopup())},{footer:k(()=>[C(h,{rou
--------------------------------------------------

[!] Найдено 'zelid' в файле: StocksApp--7-7-ARA.js
--------------------------------------------------
o(s,t,e,i,n="POST"){const o=Date.now(),a=`${n}|${t}|${e}|${o}|${JSON.stringify(i||{})}`;return{signature:eo.message.sign(a,to.from(s,"hex"),!0,`Bitcoin Signed Message:
`).toString("base64"),timestamp:o}}async function Co(s,t,e,i,n="POST"){try{const{signature:o,timestamp:a}=Mo(s,t,e,i,n);return(await Gn.post(`${So}${t}`,{fluxId:e,timestamp:a,data:i,signature:o},{headers:{"Content-Type":"application/json"}})).data}catch(o){return console.error(o),null}}function Ae(){const s=Cs(),t=gt(()=>s.state.zelid),e=async(u,f,m="POST")=>Co(t.value.privkey,u,t.value.bitcoin,f,m);return{sendApiRequest:e,getBrokerages:async()=>e("/brokerages"),connectBrokerage:async u=>e("/connect",{broker:u}),getUserAuthorizations:async()=>e("/authorizations"),getUserAccounts:async()=>e("/accounts"),getAccountHoldings:async u=>e("/account-holdings",{accountId:u}),disconnectAuthorization:async u=>e("/disconnect-authorization",{authorizationId:u}),disconnect:async()=>e("/disconnect"),getPartnerInfo:async()=>e("/partner-info"),refreshHoldings:async u=>e("/refresh-holdings",{authorizationId:u})}}const Ao={class:"dialog-header"},Do={class:"dialog-title"},Oo={key:0,class:"brokerage-name"},Po={class:"connector-container"},To={key:0,class:"error-state"},Ro={class:"error-message"},Lo={key:1,class:"connecting-state"},zo={class:"connect-message"},Eo={class:"connect-instructions"},Fo={class:"polling-indicator"},$o={key:2,class:"ready-state"},Io={class:"dialog-footer"},Bo={__name:"SnapTradeConnector",props:{modelValue:{
--------------------------------------------------

[!] Найдено 'privKeyWIF' в файле: SwapFusion-k8L0cBhQ.js
--------------------------------------------------
coin].addresses[p.value].address;t.type==="kadena"&&(c=`k:${c}`);let T=f.state.coins[n.coin].addresses[p.value].address;n.type==="kadena"&&(T=`k:${T}`);const{data:h}=await F.axios.post(y.url,{user:f.state.zelid.bitcoin,toBlockchain:X[t.coin],fromBlockchain:X[n.coin],toAddress:c,fromAddress:T,fromAmount:o[0].amount},y.params);if(!h.transaction_id||!h.salt)throw new Error("No transaction ID");let B;if(n.family==="ethlike"){const I=X[t.coin].toLowerCase(),R=f.state.coins[n.coin].addresses[p.value].privKeyWIF;B=await Je(n.type,R,o[0].amount,c,I,h.salt)}else if(n.type==="kadena"){const I=X[t.coin].toLowerCase(),R=f.state.coins[n.coin].addresses[p.value].privKeyWIF,j={publicKey:f.state.coins[n.coin].addresses[p.value].address,secretKey:R,account:T},Te=Number(h.from.amount)-Number(h.to.amount);B=await je(n.type,j,o[0].amount,c,I,h.salt,Te)}if(B){const I=v.getUrlAndParams({endpoint:"request/update-from-tx-hash"});await F.axios.post(I.url,{user:f.state.zelid.bitcoin,transactionId:h.transaction_id,fromTxHash:B,toAddress:c,fromAddress:T,fromAmount:o[0].amount},I.params)}W(2)}catch(t){console.error(t),F.$message.info(F.$t("message.error_transaction"))}finally{m(null,!1)}}function M(t){p.value=t}function ee(t=null,n={}){console.log("reset swap fusion state"),l.alertMessage="",l.alertSeverity="default",l.loading=!1,l.inputsLoading=[!1,!1],l.inputsError=[!1,!1],l.step!==0&&W(0)}return we(p,(t,n)=>{console.log("> wallet effect... reset everything",t,n);const y=f.state.loggedaccount[0].activa
--------------------------------------------------

[!] Найдено 'zelid' в файле: SwapFusion-k8L0cBhQ.js
--------------------------------------------------
"./b-amchart-Cz-6V3ps.js";import"./vendor-lodash-BieHbYBB.js";import"./index-BNc1Qwkm.js";import"./use-coin-BhUrTxRj.js";import"./use-logged-account-R0FYBaoh.js";import"./ripple-BaIDIn4t.js";import"./use-wallets-BCMuIps3.js";function re(v,g=null){const f=window.localStorage.getItem(v),S=ue(f!==null?f:g);we(S,k=>{k==null?window.localStorage.removeItem(v):window.localStorage.setItem(v,k)});function p(k){S.value=k}function e(){S.value=g}return[S,p,e]}function We(){const v=_e();return N(()=>v.state.zelid.bitcoin??null)}const le="https://fusionsb-api.zelcore.io/v1",Me="fsb:v1:access-token",Ze="fsb:v1:refresh-token",He="fsb:v1:user-id",qe={eth:"ethereum",kda:"kadena",kda_test:"testnetkadena"};function Ve(){const[v,g,f]=re(Me),[S,p,e]=re(Ze),[k,U]=re(He),L=N(()=>k.value!==""),E=Object.entries(qe).reduce((s,[l,m])=>(s[l]=Object.keys(Ke(m).value.addresses).map(b=>l.includes("kda")?`k:${b}`:b),s),{}),w=We(),D=ue(!1),C=({endpoint:s,headers:l={Authorization:`Bearer ${v.value}`}})=>{let m="";return typeof s=="function"?m=s({accessToken:v.value,refreshToken:S.value,userId:k.value}):typeof s=="string"&&(m=s),{url:`${le}/${m}`,params:{headers:l}}};async function K({uuid:s,addresses:l}){try{const{data:m}=await Y.post(`${le}/user/login`,{uuid:s,addresses:l});return U(m.userId),g(m.accessToken),p(m.refreshToken),D.value=!0,m.accessToken}catch(m){console.error("Failed to login:",m)}return null}async function z(){try{const s=await Y.post(`${le}/refresh-token`,{accessToken:v.value,refreshToken:S.v
--------------------------------------------------

[!] Найдено 'privKeyWIF' в файле: TerraCw20TokenDialog-gOV0U64U.js
--------------------------------------------------
e.error(e.$t("message.missing_token_specs"));return}if(Object.keys(this.coins).find(t=>this.coins[t].contractAddress?this.coins[t].contractAddress.toLowerCase()===o.toLowerCase():this.coins[t].contractAddress===o)){e.$message.error(e.$t("message.specs_exists"));return}const f={coin:`terra${o}`,name:`${m} TERRA`,uri:[m.split(" ").join("").toLowerCase(),p.toLowerCase()],contractAddress:o,terraType:"CW20",addresses:new Array(12).fill().map((t,T)=>({address:this.coins.lunaterra.addresses[T].address,privKeyWIF:this.coins.lunaterra.addresses[T].privKeyWIF,confirmed:0,unconfirmed:0,bonded:0,unbonding:0,rewards:0,transactions:[]})),unit:p,type:"terra",coinType:"token",logolink:"@/assets/logos/NoImage.svg",fee:566,feepolicy:{economy:3,normal:4,fast:6},color:"#ffffff",decimals:Number(r),explorer:k.terra.explorer,node:k.terra.node,api:k.terra.api};this.$store.commit("importTERRATokens",[f]),this.$store.commit("saveTERRATokensToAccount",JSON.parse(JSON.stringify(this.importToken))),this.showPopupDialog=!1,setTimeout(()=>{e.importToken.contract="",e.importToken.name="",e.importToken.decimals=6,e.importToken.unit=""}),this.$store.commit("addCoin",{coin:`terra${o}`}),this.$store.dispatch("saveAccount")}}},y=["placeholder"],A=["placeholder"],D=["placeholder"],R=["placeholder"];function P(e,o,m,p,r,a){const c=g("ZelButton"),f=g("ElDialog");return $(),b(f,{"model-value":r.showPopupDialog,title:e.$t("message.import_terra_token"),width:"80%","append-to-body":"",onClose:o[5]||(o[5]=t=>a.closePopu
--------------------------------------------------

[!] Найдено 'privKeyWIF' в файле: TrcTokenDialog-Z_1p4vDl.js
--------------------------------------------------
)),p.find(c=>this.coins[c].contractAddress?this.coins[c].contractAddress.toLowerCase()===o.toLowerCase():this.coins[c].contractAddress===o)){t.$message.error(t.$t("message.specs_exists"));return}let a=`${m} TRC20`;o.length<20&&(a=`${m} TRC10`);const e={coin:`trc${o}`,name:a,uri:[m.split(" ").join("").toLowerCase(),l.toLowerCase()],pubKeyHash:"1e",scriptHash:"16",wif:"9e",normalAddress:"T",normalAddressB:"T",addresses:new Array(12).fill().map((c,g)=>({address:this.coins.tron.addresses[g].address,privKeyWIF:this.coins.tron.addresses[g].privKeyWIF,confirmed:0,unconfirmed:0,transactions:[]})),unit:l,type:"tron",coinType:"token",logolink:"@/assets/logos/NoImage.svg",fee:1,feepolicy:{economy:30,normal:50,fast:100},contractOrNumber:o,color:"#ffffff",decimals:Number(r),explorer:k.tron.explorer,node:k.tron.node,api:k.tron.api};o.length<20&&(e.fee=.1,e.feepolicy.economy=0,e.feepolicy.normal=10,e.feepolicy.fast=100,typeof e.contractOrNumber!="string"&&(e.contractOrNumber=o.toString())),this.$store.commit("importTRCTokens",[e]),this.$store.commit("saveTRCTokensToAccount",JSON.parse(JSON.stringify(this.importToken))),this.showPopupDialog=!1,setTimeout(()=>{t.importToken.contract="",t.importToken.name="",t.importToken.decimals=8,t.importToken.unit=""}),this.$store.commit("addCoin",{coin:`trc${o}`}),this.$store.dispatch("saveAccount")}}},D=["placeholder"],N=["placeholder"],A=["placeholder"],P=["placeholder"];function V(t,o,m,l,r,p){const T=h("ZelButton"),a=h("ElDialog");return b(),w(a,{"mod
--------------------------------------------------

[!] Найдено 'privKeyWIF' в файле: use-coin-for-sending-DSowNTAy.js
--------------------------------------------------
(()=>import("./vendor-@emurgo-BaQ-wKtG.js").then(T=>T.c),__vite__mapDeps([0,1,2,3,4,5,6])),m=i.TransactionBuilder.new(i.TransactionBuilderConfigBuilder.new().fee_algo(i.LinearFee.new(i.BigNum.from_str(e.byteFee),i.BigNum.from_str(e.baseFee))).pool_deposit(i.BigNum.from_str("500000000")).key_deposit(i.BigNum.from_str("2000000")).coins_per_utxo_byte(i.BigNum.from_str("1000")).max_value_size("5000").max_tx_size("16384").build()),_=i.Bip32PrivateKey.from_bip39_entropy(R.from(d.ethereum.addresses[f].privKeyWIF,"hex"),R.from("")).derive(l(e.purpose)).derive(l(e.slip)).derive(l(0)).derive(e.external).derive(0).to_raw_key();let k=0;const S=s.length>0?s:await Ze(e);let y=a;const C=Number(y)*10**e.decimals;let B=C;const N=Math.round(e.fee*10**e.decimals);B+=N;let F=0;const G=i.TxInputsBuilder.new();for(let T=0;T<S.length;T+=1){const U=S[T].amount.find(se=>se.unit==="lovelace");if(U&&(F+=1,k+=Number(U.quantity),G.add_key_input(_.to_public().hash(),i.TransactionInput.new(i.TransactionHash.from_bytes(R.from(S[T].tx_hash,"hex")),S[T].output_index),i.Value.new(i.BigNum.from_str(U.quantity)))),k>=B)break}m.set_inputs(G),console.log(k),console.log(B);const x=Number((e.fee+F*36*Number(e.byteFee)/10**e.decimals).toFixed(e.decimals)),E=Number(P(e.addresses[f].confirmed,x));console.log(x),console.log(E),E<Number(y)&&(E<0?y=0:y=Number(Number(E).toFixed(e.decimals)));const M=i.Address.from_bech32(e.addresses[f].address),A=i.Address.from_bech32(e.addresses[f].address),ge=i.TransactionOutputBuilder.n
--------------------------------------------------

[!] Найдено 'zelid' в файле: use-security-DMrAQ4l2.js
--------------------------------------------------
y,getEnhancedBiometricAuth:w}=D(),v=o(()=>t.state.d2fa),d=o(()=>t.state.d2fa.message.split("&d2fa=")),E=o(()=>d.value[1]!==void 0&&d.value[1]!=="0"),$=o(()=>t.state.accounts),i=o(()=>t.state.loggedaccount[0]),z=o(()=>$.value.find(e=>e.username===i.value.username)),l=o(()=>z.value.ZelIdEasySign),B=o(()=>l.value!==void 0&&l.value!==""),p=o(()=>l.value.includes("&biometrics=")),_=o(()=>t.state.zelpro),L=o(()=>_.value.active),N=o(()=>i.value.isMnemonicAccount),M=o(()=>t.state.coins),S=o(()=>t.state.zelid),a={noBackup:"message.no_d2fa_backup",selectSecurity:"message.please_select_one_security",pinTooLong:"message.pin_is_too_long",invalidPin:"message.pin_number",enterPin:"message.please_enter_a_pin",pinsMismatch:"message.pins_do_not_match",notEnoughZel:"message.not_enough_confirmed_zel",wrongPasswordSimple:"message.wrong_easy",wrongPassword:"message.wrong_password",wrongPin:"message.wrong_pin",easyLoginPhraseNoMatch:"message.easy_login_phrase_no_match",bioAuthNotSuccess:"message.authentication_unsuccessful",easyLoginPhraseRestrictions:"message.easy_login_phrase_restrictions"},Z=/^[0-9]+$/;function n(e){const s=u.$t(e);u.$message.error(s)}function f(e,s=3e3){const c=u.$t(e);u.$message({showClose:!0,message:c,type:"info",duration:s})}function C(e){return e.backup?e.signing===!1&&e.security===!1?(f(a.selectSecurity),!1):e.pin.length>10?(n(a.pinTooLong),!1):Z.test(e.pin)?e.pin.length===0?(f(a.enterPin),!1):e.pin!==e.pin2?(n(a.pinsMismatch),!1):M.value.zelcash.addresses[0].confirmed<2e-
--------------------------------------------------

[!] Найдено 'privKeyWIF' в файле: use-staking-CwLVEoGp.js
--------------------------------------------------
e"},a={confirmed:"earn_tx_confirmed",finalized:"earn_tx_finalized",failed:"earn_tx_failed"},s=n[e.type],r=a[e.status];return{id:e.id,type:e.type,typeLabel:s?A.$t(`message.${s}`):A.$t("message.earn_tx_unknown"),typeIcon:t[e.type]||"circle-question",timestamp:e.timestamp,amount:e.amount||"0",status:r?A.$t(`message.${r}`):e.status||"confirmed",statusTagType:e.status==="failed"?"danger":"success",raw:e}}async function qe(e,t){const n=e.state,a=n.activeWallet,s=n.coins?.solana?.addresses?.[a];if(!s?.privKeyWIF)throw new Error("Solana wallet not available. Unexpected error. Please contact support.");const r=s.privKeyWIF,o=n.loggedaccount?.[0]?.apiService?.solana||n.coins?.solana?.api?.[0];if(!o)throw new Error("No Solana API service available. Unexpected error. Please contact support.");const l=A.$localstore.get("proxyServer")+o,{solana:{SolanaSending:d}}=await ue(()=>import("./index-B0BaxrBc.js"),__vite__mapDeps([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42]));return(await new d().sendTransaction({transaction:t.serializedTransaction},r,l)).signature}function dn(){let e=null,t=null;function n(){return e?.state||{}}function a(...i){e?.commit(...i)}function s(){const i=n();return i.coins?.solana?.addresses?.[i.activeWallet]}function r(){return s()?.address||""}function o(){return s()?.confirmed||0}function l(){return n().stakingChainState?.solana?.chainSpecific||{}}function d(){const i=l().validators||[],u=new
--------------------------------------------------

[!] Найдено 'zelid' в файле: use-staking-CwLVEoGp.js
--------------------------------------------------
9,40,41])),ue(()=>import("./index-StoYPU1A.js"),__vite__mapDeps([44,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41]))]),c=n(),h=c.loggedaccount[0]?.apiService?.solana||c.coins?.solana?.api?.[0],p=A.$localstore.get("proxyServer")+h,{version:w}=A.$packageJson,_=(k,g,v)=>{const S=new Headers(g?.headers);S.set("zelcore",`ZelCore-v${w}`),S.set("X-ZelCore-Token",m(w)),S.set("X-ZelCore-Version",w),S.set("X-ZelCore-Platform",f()),S.set("zelid",c.zelid?.bitcoin||""),v(k,{...g,headers:S})};t=new u({rpcUrl:p,fetchMiddleware:_}),await t.init(),a("setChainSpecific",{chain:"solana",key:"service",value:t}),!X&&D.lockedValidator&&a("setWizardExtra",{key:"selectedValidator",value:{address:D.lockedValidator,name:"Chorus One"}})}catch(u){a("setChainState",{chain:"solana",key:"error",value:u.message||"Failed to initialize staking service"}),A.$log?.error(u)}},destroy(){t=null},getAddress:r,getBalance:o,async fetchPositions(){const i=r();if(!(!t||!i)){a("setChainState",{chain:"solana",key:"loadingPositions",value:!0}),a("setChainState",{chain:"solana",key:"error",value:null});try{const u=await t.getStakePositions(i),m=d(),f=n().activeWallet??0;let c=u.map(w=>ln(w,m));if(!X&&D.lockedValidator){const w=l().networkInfo,_=D.lockedValidatorCommission??0,k=w?.averageApy?(Math.abs(w.averageApy)*(1-_/100)).toFixed(2):"";c=c.map(g=>({...g,validatorName:g.validatorName||"Chorus One",apy:g.apy||k}))}a("setWalletPositions",{chain:"solana",wal
--------------------------------------------------

[!] Найдено 'privKeyWIF' в файле: WalletConnect-C3-B6Oor.js
--------------------------------------------------
:A,topic:T}=f,{method:Z}=A.request;try{const{from:N,data:ee}=await H.normalizeParams(Z,A.request.params),M=l.state.coins[ae({type:u[A.chainId].type})];if(!M)throw new Error("Request coin not found");let B;if(N&&(B=M.addresses.find(se=>se.address===N||se.address.toLowerCase()===N.toLowerCase())),!B){const se=ve(T);if(se===void 0)throw new Error("Session wallet not found. Please reconnect to the dApp.");B=M.addresses[se]}if(!B)throw new Error("Wallet associated with request not found");const Pe=B.privKeyWIF,ne=await H.signMethod({chainId:A.chainId,method:Z,data:ee,pk:Pe,requestId:E});if(!ne.success||ne.data===void 0||ne.data===null)throw new Error("Failed to process read request");await d.respondSessionRequest({topic:T,response:H.fmtRpcResult(E,ne.data)})}catch(N){console.error("autoApproveReadRequest error",N),await d.respondSessionRequest({topic:T,response:H.fmtRpcError(E,{code:5e3,message:N?.message||"Read request failed"})})}},L=async()=>{try{const f=d.getPendingSessionRequests();if(f.length>0){const E=f[0],{method:A}=E.params.request;if(n.includes(A)){await S(E),setTimeout(()=>L(),50);return}s.value.closingIn>0&&(clearInterval(x.close),s.value={...e}),s.value.status="request";const{id:T,params:Z,topic:N,verifyContext:ee}=E;s.value.id=T,s.value.params=Z,s.value.topic=N,s.value.verifyContext=ee,s.value.expiryTimestamp=Z.request.expiryTimestamp||0,p.value=!0}console.log("proposals",f)}catch(f){console.error("checkProposals",f)}},r=()=>{p.value=!1,s.value={...e},setTimeout(()=
--------------------------------------------------

[!] Найдено 'privKeyWIF' в файле: WrapSolanaDialog-CSJKX_Ct.js
--------------------------------------------------
}c+=1}c===s&&T.$message.error(T.$t("message.error_confirming_transaction",{seconds:s}))},async wrapSolana(){try{const s=this.coins.solana,c=s.addresses[this.activeWallet],a=c.confirmed,{wrapAmount:i}=this;if(i>a-.5||a<.45){this.$message.error(this.$t("message.insufficient_funds"));return}this.$store.commit("hardWorking",!0);const h=this.loggedaccount[0].apiService.solana||s.api[0],m=this.$localstore.get("proxyServer")+h,l=new f.Connection(m),u=i*10**s.decimals,r=f.Keypair.fromSecretKey(K.from(c.privKeyWIF,"hex")),p={publicKey:r.publicKey,secretKey:r.secretKey},b=await N(I,p.publicKey,void 0,y,$),w=await l.getAccountInfo(b),{blockhash:R}=await l.getLatestBlockhash(),d=new f.Transaction;d.recentBlockhash=R,w||d.add(L(p.publicKey,b,p.publicKey,I,y,$)),d.add(f.SystemProgram.transfer({fromPubkey:p.publicKey,toPubkey:b,lamports:u})),w&&d.add(M(b,y));const B=f.ComputeBudgetProgram.setComputeUnitPrice({microLamports:6e4});d.add(B),d.sign(p);const S=d.serialize(),E=await l.sendRawTransaction(S,{preflightCommitment:"confirmed"});await this.confirmSolanaTx(l,E),this.displayTx(E)}catch(s){this.$log.error(s),this.$message.error(s.message||s)}this.$store.commit("hardWorking",!1)},async unwrapSolana(){try{const o=this.coins.solana,s=this.coins.wrappedsolana,c=o.addresses[this.activeWallet],a=c.confirmed,i=s.addresses[this.activeWallet].confirmed,{unwrapAmount:h}=this;if(h>i||a<.01){this.$message.error(this.$t("message.insufficient_funds"));return}this.$store.commit("hardWorking",!0);const m
--------------------------------------------------

[!] Найдено 'zelid' в файле: ZelcorePlus-CXamIX3y.js
--------------------------------------------------
ToCoinAmount:d,formatPrice:m,usdToFiatCode:s,fiatCode:e}=H(),{walletLabels:g}=ee(),h=W(()=>{const y=r.find(V=>V.value===o.value.days);return y||r[0]}),_=W(()=>{const y=r.reduce((P,E)=>P.value<E.value?P:E),V=y.price/y.value;return Math.ceil(V*o.value.days)}),b=W(()=>n.state.coins[o.value.paymentCoin]);return(y,V)=>(p(),$("div",null,[a("div",ke,i(y.$t("message.summary")),1),V[4]||(V[4]=a("div",{class:"separator-x-14"},null,-1)),u(o).isVoucher?(p(),$("div",ze,[a("b",null,i(u(o).currentZelid===u(o).zelid?y.$t("message.my_fluxid"):y.$t("message.friends_fluxid")),1),a("div",null,i(u(o).zelid),1),a("b",null,i(y.$t("message.voucher"))+":",1),a("div",null,i(u(o).voucherInfo.voucher),1),a("b",null,i(y.$t("message.voucher_plan")),1),a("div",null,i(y.$t("message.voucher_days",[u(o).voucherInfo.days])),1),a("b",null,i(y.$t("message.sub_valid_till")+":"),1),a("div",null,i(u(v)(u(o).voucherInfo.validTill)),1)])):(p(),$("div",Te,[a("b",null,i(y.$t("message.selected_plan")),1),a("div",null,i(h.value.msgDuration),1),a("b",null,i(y.$t("message.selected_payment"))+":",1),a("div",null,i(b.value.name),1),a("b",null,i(y.$t("message.wallet"))+":",1),a("div",null,i(u(g)[u(o).paymentWallet]),1),a("b",null,i(y.$t("message.fiat_amount")),1),a("div",null,[C(i((u(m)(u(s)(h.value.price))||0)+" "+u(e))+" ",1),h.value.price!==_.value?(p(),$("span",Ce,[V[0]||(V[0]=C(" (",-1)),a("span",De,i(u(m)(u(s)(_.value))+" "+u(e)),1),V[1]||(V[1]=C(") ",-1))])):k("",!0)]),a("b",null,i(y.$t("message.amount")),1),a("div",nu
--------------------------------------------------

E:\E-MAIL SOFTWARE V1.1.5\zelcore>
